#!/bin/bash

red_text() {
    echo -e "\e[31m$1\e[0m"
}

#!/bin/bash

# Get the current user's home directory
HOME_DIR="$HOME"

# Set the directory to compare against
SKEL_DIR="/etc/skel"

start_update() {
    # Update already installed axos packages
    pacman -Sy --noconfirm --needed $(comm -12 <(pacman -Slq axos | sort) <(pacman -Qq | sort))
    cp -r -u -p "$SKEL_DIR"/.local "$HOME_DIR"
    cp -r -u -p "$SKEL_DIR"/.config "$HOME_DIR"
    cp -r -u -p "$SKEL_DIR"/.bashrc "$HOME_DIR"
    echo "Done!"
}

echo "This script will update AxOS look and configurations."
echo "$(red_text 'Some user settings might be overrided.')"
echo "Your personal files will not be affected."
read -p "Continue? (Y/n): " choice

case "$choice" in
  y|Y|yes|Yes ) start_update ;;
  * ) echo "Exit.";;
esac