#!/bin/bash

red_text() {
    echo -e "\e[31m$1\e[0m"
}

echo "This script will update AxOS look and configurations."
echo "$(red_text 'Some user settings might be overrided.')"
echo "Your personal files will not be affected."
read -p "Continue? (Y/n): " choice

case "$choice" in
  y|Y|yes|Yes ) axos-hooks-runner reload-theme ;;
  * ) echo "Exit.";;
esac